const links = [
  {
    name: 'zelengora',
    heading: 'Zelengora',
    text: 'Pešačka tura Zelengora 2019',
    url: '/zelengora',
    css_class: 'img7',
    intro: 'Maksa, Djole i ekipa na hiking turi',
    autor: 'piskaranje i slike by Maksa',
    datum: 'leto 2019',
  },
  {
    name: 'fruška gora',
    heading: 'fruška gora',
    text: 'naša draga fruška gora',
    url: '/fruska_gora',
    css_class: 'img0',
    intro:
      'Bez preciznog plana, bez mape, oskudno opremljeni i sa tankim iskustvom Maksa i Zoran u oazi netaknute, predivne i surove prirode - stanište poskoka, šakala, slepih miševa i lisica - u potrazi za avanturom.',
    autor: 'Writings and photos by Zoran Lazarević',
    datum: 'Septembar 2013',
  },
  {
    name: 'lazarev kanjon',
    heading: 'istok',
    text: ' Južni Kučaj, Istočna Srbija',
    url: '/lazarev_kanjon',
    css_class: 'img1',
    intro:
      '  7 Sati ujutro. Maksa pristiže, spakovani smo i spremni za polazak u do sada najveću avanturu. Odredište je grad Zlot-Lazareva pećina, Istočni deo Srbije, najredje naseljeno područje ljudima ali vegetacija kao i životinjski svet buja što je definitivno jedan od razloga zašto smo se tamo uputili. Zlot je udaljen 220km od Beograd i putovaćemo mimo glavnih puteva.',
    autor: 'Writings and photos by Zoran Lazarević',
    datum: '11-15. avg. 2014',
  },
  {
    name: 'tara-Stara',
    heading: 'Tara',
    text: 'tura stara - stara prvi deo',
    url: '/tara_stara',
    css_class: 'img2',
    intro: 'Mire i Zoran na turi od Beograda preko Tare na Kopaonik',
    autor: 'Piskaranje i slike by Zoran Lazarevic',
    datum: 'maj 2015',
  },
  {
    name: 'putešestvije',
    heading: 'putešestvije',
    text: 'mire sa "krmačicom" na velikoj balksanskoj turi ~3000km',
    url: '/putesestvije',
    css_class: 'img3',
    intro: 'Mire na putu po balkanskom polustrvu',
    autor: 'Piskaranje i slike by Zoran Lazarevic',
    datum: 'avgust 2019',
  },
  {
    name: 'stara',
    heading: 'stara',
    text: 'tura tara - stara drugi deo',
    url: '/stara',
    css_class: 'img4',
    intro:
      'Mire i Zoran na turi od Kursumlije do Stare Koridorom 10, ~170km u spakovanih u 5 dana',
    autor: 'Piskaranje i slike by Zoran Lazarevic',
    datum: 'avgust 2016',
  },
  {
    name: 'vlasina',
    heading: 'Vlasina',
    text: 'mire i zoran u pohodu na Vlasinu',
    url: '/vlasina',
    css_class: 'img5',
    intro:
      'od leskovca preko vlasotinca do vlasinskog jezera ~120mnv pa preko Surdulice i Gadzinog hana na Prokuplje i Kursumliju',
    autor: 'Piskaranje i slike by Zoran Lazarevic',
    datum: 'jul 2019',
  },
  {
    name: 'vinatovača',
    heading: 'vinatovača',
    text: 'prašuma Vinatovača',
    url: '/vinatovaca',
    css_class: 'img6',
    intro: 'Vinatovaca prasuma. Jedno od onih mesta gde se opet i opet vracate',
    autor: 'Piskaranje i slike by Zoran Lazarevic',
    datum: 'jul 2019',
  },
];
export default links;
